### ISSUE TITLE
version 7.1.5]PlatformException(channel-error, Unable to establish connection on channel., null, null)

### ISSUE THREAD

**Issue by mdddj** [solid-software/flutter_vlc_player#339]

**Comment by rmartinsfer** [comment]
Hi friend, I have the same problem, did you manage to solve it?

**Comment by mdddj** [comment]
> 

Hello friend, yes, I solved it. It seems that there is a logic error in native Android

**Comment by mdddj** [comment]
I tried to find the solved source code on the local machine, but I'm sorry. It seems that I deleted it one day ago

**Comment by rmartinsfer** [comment]
Thank you very much, it is already a way for me to try to solve this problem.

**Comment by rmartinsfer** [comment]
Can you remember, in which part of the native android?

**Comment by mdddj** [comment]
> Can you remember, in which part of the native android?

You can try to delete this line, which should solve the problem



https://github.com/solid-software/flutter_vlc_player/blob/07532cb8835a32393f421761447a6649c561d99e/flutter_vlc_player/android/src/main/java/software/solid/fluttervlcplayer/FlutterVlcPlayerPlugin.java#L53

**Comment by rmartinsfer** [comment]
I still have the same error, is there anything else to modify, but thanks for the help.

**Comment by elia-driesner** [comment]
> I still have the same error, is there anything else to modify, but thanks for the help.

Hi, i know its a little late but did you solve the problem, i am developing for ios and android and both are not working.
